#
# Ansible Playbook for Subutai IPFS blueprint
#
---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: ipfs
  remote_user: root
  tasks: 

    - name: Install required debs
      apt: 
        name: "{{ item }}"
        state: present
      with_items: 
        - golang-1.10
        - apache2
        - git

    - name: Set go version
      alternatives:
        name: go
        path: /usr/lib/go-1.10/bin/go
        link: /usr/bin/go
        priority: 10

    - name: Install ipfs-update
      command: go get -u github.com/ipfs/ipfs-update
      args: 
        creates: go/bin/ipfs-update

    - name: Install ipfs
      command: go/bin/ipfs-update install latest
      args: 
        creates: /usr/local/bin/ipfs

    - name: Initialize ipfs
      command: /bin/bash -c "IPFS_PATH=/root/.ipfs ipfs init"
      args: 
        creates: .ipfs/

    - name: Install ipfs default
      template:
        src: files/ipfs.default
        dest: /etc/default/ipfs

    - name: Install ipfs systemd unit
      template: 
        src: files/ipfs.service
        dest: /lib/systemd/system

    - name: Reload systemd
      systemd: daemon_reload=yes

    - name: Enable and start ipfs daemon
      systemd:
        name: ipfs
        state: started
        enabled: true
        masked: no
        
# vim: ts=2 et nowrap autoindent